amcl:
  ros__parameters:
    use_sim_time: false
    laser_model_type: "likelihood_field"
    min_particles: 500
    max_particles: 2000
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    scan_topic: "scan"
    set_initial_pose: true

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/afsalu-rahman-c/final_project_phase2_ws/src/fp_darc/maps/elextron.yaml  "

map_saver:
  ros__parameters:
    use_sim_time: false
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: true

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: "map"
    robot_base_frame: "base_footprint"
    default_bt_xml_filename: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"


controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false
      min_vel_x: 0.0
      max_vel_x: 0.26
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      min_speed_theta: 0.0
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_theta: -3.2
      vx_samples: 20
      vtheta_samples: 40
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]

      RotateToGoal:
        scale: 1.0
      Oscillation:
        scale: 1.0
      BaseObstacle:
        scale: 1.0
        sum_scores: true
      GoalAlign:
        scale: 24.0
      PathAlign:
        scale: 32.0
      PathDist:
        scale: 32.0
      GoalDist:
        scale: 24.0


planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 1.0

smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["SimpleSmoother"]

recoveries_server:
  ros__parameters:
    use_sim_time: false

global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_footprint
    update_frequency: 1.0
    publish_frequency: 1.0
    resolution: 0.05
    rolling_window: false
    width: 10
    height: 10
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: true

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: scan
        max_obstacle_height: 2.0
        clearing: true
        marking: true
        data_type: LaserScan

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.55


local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: odom
    robot_base_frame: base_footprint
    update_frequency: 5.0
    publish_frequency: 2.0
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: scan
        max_obstacle_height: 2.0
        clearing: true
        marking: true
        data_type: LaserScan

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.55
